import assert from "node:assert/strict";
import { spawn, execFileSync } from "node:child_process";
import { once } from "node:events";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const repo = fileURLToPath(new URL("../../..", import.meta.url));
const require = createRequire(path.join(repo, "app/package.json"));
const { chromium, expect } = require("@playwright/test");
const fixture = await fs.mkdtemp(path.join(os.tmpdir(), "prompt-editor-browser-"));
const artifacts = process.env.PROMPT_EDITOR_ARTIFACTS;
const git = (...args) => execFileSync("git", ["-C", fixture, ...args], { encoding: "utf8", env: { ...process.env, GIT_CONFIG_GLOBAL: os.devNull, GIT_CONFIG_NOSYSTEM: "1" } }).trim();
const root = path.join(fixture, "internal/prompts");
const wake = path.join(root, "content/crew/wake.md");
let server, browser, context;
const consoleErrors = [];
try {
  await fs.mkdir(root, { recursive: true });
  await fs.cp(path.join(repo, "internal/prompts/content"), path.join(root, "content"), { recursive: true });
  git("init", "-b", "next");
  const commit = () => {
    git("add", ".");
    git("-c", "user.name=Editor browser test", "-c", "user.email=editor@example.test", "commit", "--no-gpg-sign", "-m", "Prompt fixture");
    return git("rev-parse", "HEAD");
  };
  const legacy = commit();
  const manifest = JSON.parse(await fs.readFile(path.join(repo, "internal/prompts/catalog.generated.json"), "utf8"));
  delete manifest.definitions_hash;
  const currentManifest = JSON.stringify(manifest);
  const crew = manifest.recipients.find((r) => r.id === "crew");
  const wakeEvent = crew.events.find((e) => e.id === "wake");
  wakeEvent.delivery = "launch_instructions";
  wakeEvent.body = { kind: "compose", children: [wakeEvent.body, { kind: "input", field: { name: "old_note", kind: "text", description: "A base-only input" } }] };
  crew.events.push({ id: "retired", delivery: "user_message", description: "Removed event", body: { kind: "text", id: "retired", source: "content/retired.md" } });
  await fs.writeFile(path.join(root, "catalog.generated.json"), JSON.stringify(manifest));
  await fs.writeFile(path.join(root, "content/retired.md"), "Retired guidance.\n");
  await fs.writeFile(wake, "Wake from the common ancestor.\n");
  const ancestor = commit();
  git("checkout", "-b", "feature");
  await fs.writeFile(path.join(root, "catalog.generated.json"), currentManifest);
  await fs.writeFile(wake, "Wake from the feature branch.\n");
  const head = commit();
  git("checkout", "next");
  await fs.writeFile(wake, "Wake from the next branch tip.\n");
  const tip = commit();
  git("checkout", "feature");
  const binary = process.env.PROMPT_EDITOR_BIN || path.join(fixture, "prompt-editor");
  if (!process.env.PROMPT_EDITOR_BIN) execFileSync("go", ["build", "-o", binary, "./cmd/prompt-editor"], { cwd: repo, stdio: "inherit" });
  server = spawn(binary, ["--repo", fixture, "--base", "next"], { stdio: ["ignore", "pipe", "pipe"] });
  const url = await new Promise((resolve, reject) => {
    let stdout = "";
    const timer = setTimeout(() => reject(new Error("Editor did not start")), 15000);
    server.once("error", (error) => { clearTimeout(timer); reject(error); });
    server.once("exit", (code) => { clearTimeout(timer); reject(new Error(`Editor exited ${code}`)); });
    server.stdout.on("data", (chunk) => {
      stdout += chunk;
      const match = stdout.match(/http:\/\/127\.0\.0\.1:\d+/);
      if (match) { clearTimeout(timer); resolve(match[0]); }
    });
    server.stderr.on("data", (chunk) => process.stderr.write(chunk));
  });
  if (artifacts) await fs.mkdir(artifacts, { recursive: true });
  browser = await chromium.launch({ headless: true });
  context = await browser.newContext({ colorScheme: "light", viewport: { width: 1440, height: 1000 }, ...(artifacts ? { recordVideo: { dir: artifacts, size: { width: 1440, height: 1000 } } } : {}) });
  const page = await context.newPage();
  page.on("pageerror", (error) => consoleErrors.push(String(error)));
  await page.goto(`${url}/#crew/wake`);
  await expect(page.locator("#base-status")).toContainText(ancestor.slice(0, 8));
  await expect(page.locator("#event-change")).toHaveText("definition changed");
  await expect(page.locator("#theme")).toHaveValue("system");
  await page.emulateMedia({ colorScheme: "dark" });
  await expect(page.locator("html")).toHaveCSS("color-scheme", "dark");
  await page.locator("#theme").selectOption("light");
  await expect(page.locator("html")).toHaveCSS("color-scheme", "light");
  await page.locator("#theme").selectOption("dark");
  await page.reload();
  await expect(page.locator("#theme")).toHaveValue("dark");
  await page.emulateMedia({ colorScheme: "light" });
  await expect(page.locator("html")).toHaveCSS("color-scheme", "dark");
  await page.locator("#theme").selectOption("system");
  await expect(page.locator("html")).toHaveCSS("color-scheme", "light");
  await page.getByLabel("old_note", { exact: true }).fill("Shared scenario note.");
  await page.getByLabel("Markdown source").fill("Wake from my unsaved draft.\nLiteral <script>text</script> and λ.\n");
  await page.locator("#source-compare").click();
  await page.locator("#review-prompt").click();
  await expect(page.locator("#source-diff .added .line-text")).toContainText(["Wake from my unsaved draft.", "Literal <script>text</script> and λ."]);
  await expect(page.locator("#source-diff .removed .line-text")).toContainText(["Wake from the common ancestor."]);
  await expect(page.locator("#prompt-diff")).toContainText("Shared scenario note.");
  await expect(page.locator("#delivery")).toContainText("launch instructions → user message");
  await page.locator("#theme").selectOption("dark");
  await expect(page.locator("#source")).toHaveValue("Wake from my unsaved draft.\nLiteral <script>text</script> and λ.\n");
  await expect(page.locator("#source-diff .added").first()).toHaveCSS("color", "rgb(178, 229, 197)");
  await expect(page.locator("#source-diff .removed").first()).toHaveCSS("color", "rgb(255, 194, 205)");
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "dark-comparison.png") });
  await page.locator("#theme").selectOption("system");
  assert.equal(await fs.readFile(wake, "utf8"), "Wake from the feature branch.\n");
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "draft-comparison.png") });
  await page.locator("#changed-only").check();
  await expect(page.locator(".event-link").filter({ hasText: /^heartbeat/ })).toHaveCount(0);
  await page.locator("#review-close").click();
  await page.locator("#save").click();
  await expect(page.locator("#global-status")).toHaveText("Checkout sources");
  assert.equal(await fs.readFile(wake, "utf8"), "Wake from my unsaved draft.\nLiteral <script>text</script> and λ.\n");
  if (await page.locator("#review-close").isVisible()) await page.locator("#review-close").click();
  await page.getByLabel("Markdown source").fill("An edit to discard.");
  await page.locator("#reset").click();
  assert.match(await page.getByLabel("Markdown source").inputValue(), /^Wake from my unsaved draft/);
  await page.locator("#source-compare").click();
  await page.locator("#base-mode").selectOption("tip");
  await expect(page.locator("#base-status")).toContainText(tip.slice(0, 8));
  await expect(page.locator("#source-diff")).toContainText("Wake from the next branch tip.");
  await page.locator(".event-link").filter({ hasText: /^retired/ }).click();
  await expect(page.locator("#event-change")).toHaveText("removed");
  await expect(page.locator("#prompt-diff")).toContainText("Retired guidance.");
  await expect(page.locator("#save")).toBeDisabled();
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "removed-event.png") });
  await page.locator("#base-mode").selectOption("merge-base");
  await expect(page.locator("#base-status")).toContainText(ancestor.slice(0, 8));
  await expect(page.locator("#event-name")).toHaveText("retired");
  await expect(page.locator("#prompt-diff")).toContainText("Retired guidance.");
  await page.locator(".event-link").filter({ hasText: /^wake/ }).click();
  await page.locator("#base-ref").fill("does-not-exist");
  await page.locator("#compare-base").click();
  await expect(page.locator("#base-status")).toHaveText("Comparison unavailable");
  await expect(page.locator("#source-diff")).not.toContainText("Wake from the next branch tip.");
  await page.locator("#base-ref").fill(legacy);
  await page.locator("#compare-base").click();
  await expect(page.locator("#base-error")).toContainText("no catalog manifest");
  await expect(page.locator("#prompt-diff")).toContainText("Composed comparison unavailable");
  await expect(page.locator("#source-diff .added")).toContainText(["Wake from my unsaved draft.", "Literal <script>text</script> and λ."]);
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "legacy-base.png") });
  await page.locator("#clear-base").click();
  await expect(page.locator("#base-error")).toBeHidden();
  if (await page.locator("#review-close").isVisible()) await page.locator("#review-close").click();
  await expect(page.locator("#output")).toContainText("Wake from my unsaved draft.");
  await page.getByLabel("Markdown source").fill("Stale draft.");
  await fs.writeFile(wake, "External edit.\n");
  await page.locator("#save").click();
  await expect(page.locator("#file-error")).toContainText("file changed on disk");
  assert.equal(await fs.readFile(wake, "utf8"), "External edit.\n");
  page.on("dialog", (dialog) => dialog.accept());
  await page.locator("#reload").click();
  await expect(page.getByLabel("Markdown source")).toHaveValue("External edit.\n");
  const contextBefore = "# Purpose\n\nEvery seed is a prompt for a fresh agent.\n\n## Shared decisions\n\nKeep the common design in the parent plot.\nRead the named sections before starting.\nUse the child body to define this assignment.\nRecord evidence on the seed.\n\n## Child assignment\n\n";
  const contextAfter = "\n\n## Verification\n\nDescribe how the result will be checked.\nPreserve the agreed scope.\nName the artifact the next agent needs.\n\n## Handover\n\nThe final section must remain readable outside the changed hunk.\n";
  const baseText = contextBefore + "Write an outcome." + contextAfter;
  const currentText = contextBefore + "Write a complete work prompt with its outcome and required reading." + contextAfter;
  await fs.writeFile(wake, baseText);
  const contextBase = commit();
  await page.reload();
  await expect(page.getByLabel("Markdown source")).toHaveValue(baseText);
  await page.getByLabel("Markdown source").fill(currentText);
  await page.locator("#base-ref").fill(contextBase);
  await page.locator("#compare-base").click();
  await expect(page.locator("#base-status")).toContainText(contextBase.slice(0, 8));
  await page.locator("#source-compare").click();
  await expect(page.getByLabel("Full source text", { exact: true })).toHaveValue(currentText);
  await expect(page.locator("#source-diff")).not.toContainText("The final section must remain readable");
  await expect(page.locator("#source-diff")).toContainText("Write a complete work prompt");
  const fullBounds = await page.locator(".full-text-pane").boundingBox();
  const diffBounds = await page.locator(".review-diff-pane").boundingBox();
  assert.ok(fullBounds.width > 500 && diffBounds.x >= fullBounds.x + fullBounds.width, "full text and diff need readable adjacent columns");
  const diffEditedText = contextBefore + "Write a complete work prompt while reading its diff." + contextAfter;
  await page.getByLabel("Full source text", { exact: true }).fill(diffEditedText);
  await expect(page.locator("#source")).toHaveValue(diffEditedText);
  await expect(page.locator("#source-diff")).toContainText("while reading its diff");
  await page.locator("#review-save").click();
  await expect(page.locator("#global-status")).toHaveText("Checkout sources");
  assert.equal(await fs.readFile(wake, "utf8"), diffEditedText);
  await page.locator("#review-version").selectOption("base");
  await expect(page.locator("#review-full-text")).toHaveValue(baseText);
  await expect(page.locator("#review-full-text")).toHaveJSProperty("readOnly", true);
  await page.locator("#review-version").selectOption("current");
  await expect(page.locator("#review-full-text")).toHaveJSProperty("readOnly", false);
  await page.locator("#review-full-text").focus();
  await page.keyboard.press("Escape");
  await expect(page.getByLabel("Markdown source")).toHaveValue(diffEditedText);
  await expect(page.locator("#source-compare")).toBeFocused();
  await page.locator("#prompt-compare").click();
  await expect(page.getByLabel("Full composed prompt", { exact: true })).toHaveValue(/The final section must remain readable/);
  await expect(page.locator("#prompt-diff")).toContainText("while reading its diff");
  await page.locator("#review-version").selectOption("base");
  await expect(page.locator("#review-full-text")).toHaveValue(/Write an outcome\./);
  await page.locator("#review-version").selectOption("current");
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "full-prompt-comparison.png") });
  await page.locator("#review-source").click();
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "full-source-comparison.png") });
  await page.setViewportSize({ width: 780, height: 900 });
  await expect(page.locator("#review-full-text")).toBeVisible();
  await expect(page.locator("#source-diff")).toBeVisible();
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "narrow-full-comparison.png"), fullPage: true });
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.locator("#review-close").click();
  let requests = 0;
  page.on("request", () => requests++);
  await expect(page.locator("#output")).toContainText("Write a complete work prompt while reading its diff");
  const settled = requests;
  const idleBefore = execFileSync("ps", ["-p", String(server.pid), "-o", "rss=", "-o", "time="], { encoding: "utf8" }).trim();
  await page.waitForTimeout(1200);
  const idleAfter = execFileSync("ps", ["-p", String(server.pid), "-o", "rss=", "-o", "time="], { encoding: "utf8" }).trim();
  assert.equal(requests, settled, "editor polls while idle");
  assert.equal(git("rev-parse", "HEAD"), contextBase);
  assert.deepEqual(consoleErrors, []);
  await page.setViewportSize({ width: 780, height: 900 });
  if (artifacts) await page.screenshot({ path: path.join(artifacts, "narrow-editor.png"), fullPage: true });
  console.log(JSON.stringify({ status: "passed", ancestor, head, tip, legacy, consoleErrors, idleRequests: requests - settled, idleBefore, idleAfter, artifacts }, null, 2));
} finally {
  if (context) await context.close();
  if (browser) await browser.close();
  if (server && server.exitCode === null) { server.kill("SIGTERM"); await once(server, "exit"); }
  await fs.rm(fixture, { recursive: true, force: true });
}
