package appbuild

import (
	"fmt"
	"strings"

	"github.com/victorarias/attn/internal/apps"
)

const (
	GeneratedFile = "src/generated.ts"

	SDKModule = "@victorarias/attn-app"

	generatedHeader = "// Generated by attn from " + ManifestName + ". Do not edit — `attn app apply` rewrites it.\n"
)

// SDKSpecifiers is every specifier a view may import. The view build's externals, the
// materialized package's exports map, and the frontend's import map must all agree.
func SDKSpecifiers() []string {
	return []string{SDKModule, SDKModule + "/jsx-runtime", SDKModule + "/jsx-dev-runtime"}
}

func GenerateTypes(m Manifest) string {
	var b strings.Builder
	b.WriteString(generatedHeader)
	b.WriteString("//\n")
	b.WriteString(fmt.Sprintf("// app %s — bus consumer %s, documents under %s\n",
		m.Name, apps.ConsumerName(m.Name), apps.Namespace(m.Name)))
	b.WriteString("\n")
	b.WriteString(fmt.Sprintf("import type { AppContext, AppEvent, Collection, ReconcileHandler } from %q\n\n", SDKModule))

	b.WriteString("// The collections this app declared. Reachable as ctx.collections.<name>;\n")
	b.WriteString("// a name that is not declared is a compile error, not an empty read.\n")
	b.WriteString("export type AppCollections = {\n")
	for _, c := range m.Collections {
		b.WriteString(fmt.Sprintf("  %s: Collection\n", tsKey(c.Name)))
	}
	b.WriteString("}\n\n")

	b.WriteString("// The context every handler of this app receives.\n")
	b.WriteString("export type Ctx = AppContext<AppCollections>\n\n")

	b.WriteString("// One group per kind, one entry per declaration. The entrypoint's default\n")
	b.WriteString("// export must `satisfies Handlers`, so a declaration with no handler, a\n")
	b.WriteString("// handler with the wrong shape, and a handler nothing declared are all\n")
	b.WriteString("// compile errors here rather than silence at runtime.\n")
	b.WriteString("//\n")
	b.WriteString("// A subscription is keyed by its event pattern and a command by its bare\n")
	b.WriteString("// name. They cannot collide because they are not in the same map: which kind\n")
	b.WriteString("// is being run is what attn already knows when it dispatches.\n")
	b.WriteString("export type Handlers = {\n")
	writeHandlerGroup(&b, "subscriptions", m.EventPatterns(),
		"(event: AppEvent, ctx: Ctx) => void | Promise<void>")
	writeHandlerGroup(&b, "commands", m.CommandNames(),
		"(payload: unknown, ctx: Ctx) => unknown")
	if m.Reconcile {
		b.WriteString("  reconcile: ReconcileHandler<AppCollections>\n")
	} else {
		b.WriteString("  reconcile?: never\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func writeHandlerGroup(b *strings.Builder, group string, keys []string, signature string) {
	if len(keys) == 0 {
		b.WriteString(fmt.Sprintf("  %s?: Record<string, never>\n", group))
		return
	}
	b.WriteString(fmt.Sprintf("  %s: {\n", group))
	for _, key := range keys {
		b.WriteString(fmt.Sprintf("    %s: %s\n", tsKey(key), signature))
	}
	b.WriteString("  }\n")
}

func tsKey(s string) string { return fmt.Sprintf("%q", s) }
