import fs from 'node:fs';
import path from 'node:path';
import { execFileSync } from 'node:child_process';

import { harnessArtifactsRoot } from './common.mjs';
import { MOCK_AGENT_AGENTS, MOCK_AGENT_EXECUTABLE } from './mockAgent.mjs';
import { appDaemonInTree } from './platform.mjs';
import { assertFreshWorldTargetSafe } from './freshWorld.mjs';
import { MOCK_GITHUB_URL_VAR } from './mockGitHub.mjs';
import {
  currentHarnessProfile,
  daemonPidFilePathForProfile,
  defaultAppPathForProfile,
  profileCliEnv,
} from './harnessProfile.mjs';

export const TRIPWIRE_BINARIES = ['claude', 'codex', 'copilot', 'pi'];

// Not 1 and not 127: an agent binary that fails on its own, or is missing, must
// stay distinguishable from one the tripwire refused to run.
export const TRIPWIRE_EXIT_CODE = 97;

export const TRIPWIRE_MARKER_VAR = 'ATTN_AGENT_TRIPWIRE';
export const TRIPWIRE_LEDGER_NAME = 'agent-tripwire.ledger';

// internal/headless: `off` makes the daemon refuse every headless LLM task
// (narration, classifier, title, reconcile) and log the refusal.
export const HEADLESS_TASKS_VAR = 'ATTN_HEADLESS_TASKS';

// A real `attn agent claude` launch measured 8584 bytes of argv (the appended
// system prompt); the ledger names what ran, it does not archive it.
const LEDGER_ARGV_CHARS = 512;

const POINTER_FILE = 'current-run';
const UNATTRIBUTED_LEDGER = 'unattributed.ledger';

// The Go drivers read the first three (internal/agent/resolve.go); the attn-pi
// plugin reads ATTN_PI_EXECUTABLE (plugins/attn-pi/src/driver.ts).
const EXECUTABLE_VARS = {
  claude: 'ATTN_CLAUDE_EXECUTABLE',
  codex: 'ATTN_CODEX_EXECUTABLE',
  copilot: 'ATTN_COPILOT_EXECUTABLE',
  pi: 'ATTN_PI_EXECUTABLE',
};

// One dir for every scenario: the daemon outlives a scenario, so it keeps the
// PATH and overrides of whichever run started it.
export function tripwireDir(env = process.env) {
  return path.join(harnessArtifactsRoot(env), 'agent-tripwire');
}

export function armedBinaries(allowRealAgents) {
  if (allowRealAgents === undefined || allowRealAgents === null || allowRealAgents === false) {
    return [...TRIPWIRE_BINARIES];
  }
  if (allowRealAgents === true) {
    return [];
  }
  if (!Array.isArray(allowRealAgents)) {
    throw new Error(
      `allowRealAgents must be true, false, or an array of ${TRIPWIRE_BINARIES.join('/')} (got ${JSON.stringify(allowRealAgents)})`,
    );
  }
  for (const name of allowRealAgents) {
    if (!TRIPWIRE_BINARIES.includes(name)) {
      throw new Error(`allowRealAgents names an unknown agent binary ${JSON.stringify(name)}; known: ${TRIPWIRE_BINARIES.join(', ')}`);
    }
  }
  return TRIPWIRE_BINARIES.filter((name) => !allowRealAgents.includes(name));
}

export function tripwireMarker({ dir, binaries }) {
  return `${dir}|${[...binaries].sort().join(',')}`;
}

export function shimSource(name) {
  // Only pi earns a --version escape (its daemon health probe calls no model);
  // every other shim stays fail-closed, so a real --version still hits the ledger.
  const versionEscape = name === 'pi'
    ? `if [ "$#" -eq 1 ] && [ "$1" = "--version" ]; then
  rest=; IFS=:; for entry in $PATH; do [ "$entry" = "$dir" ] || rest="\${rest:+$rest:}$entry"; done; unset IFS
  real=$(PATH="$rest" command -v "${name}" 2>/dev/null) && exec "$real" --version
  exit 127
fi
`
    : '';
  return `#!/bin/sh
# Generated by app/scripts/real-app-harness/agentTripwire.mjs. The harness puts
# this dir first on PATH so a real agent exec lands in the ledger instead.
dir=$(CDPATH= cd -- "\${0%/*}" && pwd)
scenario=unattributed
ledger="$dir/${UNATTRIBUTED_LEDGER}"
if [ -r "$dir/${POINTER_FILE}" ]; then
  { read -r pointer_scenario; read -r pointer_ledger; } < "$dir/${POINTER_FILE}"
  if [ -n "$pointer_scenario" ]; then scenario="$pointer_scenario"; fi
  if [ -n "$pointer_ledger" ]; then ledger="$pointer_ledger"; fi
fi
${versionEscape}full=$(printf '%s ' "${name}" "$@" | tr '\\n\\t' '  ' | sed 's/ *$//')
argv=$(printf '%.${LEDGER_ARGV_CHARS}s' "$full")
if [ \${#full} -gt ${LEDGER_ARGV_CHARS} ]; then
  argv="$argv... (+$((\${#full} - ${LEDGER_ARGV_CHARS})) chars)"
fi
printf '%s\\t%s\\n' "$scenario" "$argv" >> "$ledger"
printf 'attn harness agent tripwire: scenario %s must not run the real %s; this run fails on it.\\nledger: %s\\n' "$scenario" "${name}" "$ledger" >&2
exit ${TRIPWIRE_EXIT_CODE}
`;
}

export function writeTripwireShims({ dir, binaries }) {
  fs.mkdirSync(dir, { recursive: true });
  for (const name of TRIPWIRE_BINARIES) {
    const shimPath = path.join(dir, name);
    if (binaries.includes(name)) {
      fs.writeFileSync(shimPath, shimSource(name), { encoding: 'utf8', mode: 0o755 });
      fs.chmodSync(shimPath, 0o755);
      continue;
    }
    fs.rmSync(shimPath, { force: true });
  }
  return dir;
}

function headlessTasksOff(binaries) {
  return binaries.length > 0;
}

export function applyTripwireEnv(env, { dir, binaries }) {
  const entries = (env.PATH || '').split(path.delimiter).filter((entry) => entry && entry !== dir);
  env.PATH = [dir, ...entries].join(path.delimiter);
  env[TRIPWIRE_MARKER_VAR] = tripwireMarker({ dir, binaries });
  if (headlessTasksOff(binaries)) {
    env[HEADLESS_TASKS_VAR] = 'off';
  } else {
    delete env[HEADLESS_TASKS_VAR];
  }
  for (const name of TRIPWIRE_BINARIES) {
    const key = EXECUTABLE_VARS[name];
    if (binaries.includes(name)) {
      // A mocked agent pins at the mock, not the shim, so the scenario gets an
      // agent; its shim stays on PATH, so a name-resolved exec still trips.
      env[key] = MOCK_AGENT_AGENTS.includes(name) ? MOCK_AGENT_EXECUTABLE : path.join(dir, name);
      continue;
    }
    // An allowed binary must resolve for real, even if an earlier scenario in
    // this shell pinned it at a shim that is now gone.
    delete env[key];
  }
  return env;
}

export function agentTripwireLaunchEnv(env = process.env) {
  const marker = env[TRIPWIRE_MARKER_VAR];
  if (!marker) {
    return {};
  }
  const launchEnv = { PATH: env.PATH, [TRIPWIRE_MARKER_VAR]: marker };
  if (env[HEADLESS_TASKS_VAR]) {
    launchEnv[HEADLESS_TASKS_VAR] = env[HEADLESS_TASKS_VAR];
  }
  for (const name of TRIPWIRE_BINARIES) {
    const key = EXECUTABLE_VARS[name];
    if (env[key]) {
      launchEnv[key] = env[key];
    }
  }
  return launchEnv;
}

export function readTripwireLedger(ledgerPath) {
  let raw;
  try {
    raw = fs.readFileSync(ledgerPath, 'utf8');
  } catch (error) {
    if (error?.code === 'ENOENT') {
      return [];
    }
    throw error;
  }
  return raw.split('\n').map((line) => line.trim()).filter(Boolean);
}

const RECEIPT_DIAGNOSIS = {
  on: 'the daemon came up without the switch, so narration, classification or titling could still have exec\'d an agent',
  'no daemon': 'no daemon was running when the scenario finished, so nothing proves what it was carrying',
  unreadable: 'the daemon environment could not be read, so nothing proves what it was carrying',
};

export function formatReceiptFailure({ scenarioId, receipt, marker, pidPath = null }) {
  const mode = receipt?.headlessTasks ?? null;
  const faults = [
    ...(mode === 'off' ? [] : [`${HEADLESS_TASKS_VAR} reads ${JSON.stringify(mode)} — ${RECEIPT_DIAGNOSIS[mode] || 'the harness never read a daemon'}`]),
    ...(receipt?.carriesMarker ? [] : [`${TRIPWIRE_MARKER_VAR} is not ${marker} — the daemon was armed by another run, or not at all`]),
  ];
  return [
    `agent tripwire: ${scenarioId} ran armed, so the daemon it ran against has to prove it carried the shims and the switch.`,
    ...faults.map((fault) => `  ${fault}`),
    ...(pidPath ? [`daemon pid file: ${pidPath}`] : []),
    'a scenario that must run a real agent declares it instead: a scenarioCatalog.mjs entry, or allowRealAgents on createScenarioRunner.',
  ].join('\n');
}

export function formatTripwireFailure({ scenarioId, ledgerPath, lines }) {
  return [
    `agent tripwire: ${lines.length} real agent exec(s) during ${scenarioId}; this run calls no model.`,
    `ledger: ${ledgerPath}`,
    ...lines.map((line) => `  ${line}`),
  ].join('\n');
}

export function armAgentTripwire({
  scenarioId,
  runDir,
  allowRealAgents,
  env = process.env,
  profile = currentHarnessProfile(),
  readReceipt = readDaemonTripwireReceipt,
  log = (message) => console.log(`[agent-tripwire] ${message}`),
}) {
  const dir = tripwireDir(env);
  const binaries = armedBinaries(allowRealAgents);
  const armed = headlessTasksOff(binaries);
  const ledgerPath = path.join(runDir, TRIPWIRE_LEDGER_NAME);
  const pidPath = daemonPidFilePathForProfile(profile);
  const marker = tripwireMarker({ dir, binaries });

  writeTripwireShims({ dir, binaries });
  fs.writeFileSync(ledgerPath, '', 'utf8');
  fs.writeFileSync(path.join(dir, POINTER_FILE), `${scenarioId}\n${ledgerPath}\n`, 'utf8');
  applyTripwireEnv(env, { dir, binaries });

  const allowed = TRIPWIRE_BINARIES.filter((name) => !binaries.includes(name));
  if (allowed.length > 0) {
    log(`REAL AGENTS ALLOWED for ${scenarioId}: ${allowed.join(', ')} — this scenario still runs a real agent binary.`);
  }
  log(`armed for ${scenarioId}: ${binaries.length > 0 ? binaries.join(', ') : '(nothing)'} — ledger ${ledgerPath}`);
  const mocked = binaries.filter((name) => MOCK_AGENT_AGENTS.includes(name));
  if (mocked.length > 0) {
    log(`${mocked.join(', ')} run the mock agent for ${scenarioId}: ${MOCK_AGENT_EXECUTABLE}`);
  }
  if (armed) {
    log(`${HEADLESS_TASKS_VAR}=off for ${scenarioId}: the daemon refuses narration, classification and every other headless task.`);
  }

  return {
    scenarioId,
    dir,
    binaries,
    allowed,
    ledgerPath,
    armed,
    pidPath,
    marker,
    read: () => readTripwireLedger(ledgerPath),
    readReceipt: () => (armed ? readReceipt({ profile, marker }) : null),
  };
}

export function readProcessEnvironment(pid, { platform = process.platform, run = execFileSync } = {}) {
  if (platform === 'darwin') {
    return String(run('ps', ['eww', '-p', String(pid)], { encoding: 'utf8' }));
  }
  return fs.readFileSync(path.join('/proc', String(pid), 'environ'), 'utf8').split('\0').join('\n');
}

function livingDaemonPid(pidPath) {
  let pid;
  try {
    pid = Number.parseInt(fs.readFileSync(pidPath, 'utf8').trim(), 10);
  } catch {
    return null;
  }
  if (!Number.isInteger(pid) || pid <= 0) {
    return null;
  }
  try {
    process.kill(pid, 0);
  } catch {
    return null;
  }
  return pid;
}

// The daemon reads both variables out of its own environment, so that
// environment is the receipt that they were in force for the whole run.
export function readDaemonTripwireReceipt({
  marker = null,
  profile = currentHarnessProfile(),
  pidPath = daemonPidFilePathForProfile(profile),
  readEnvironment = readProcessEnvironment,
} = {}) {
  const pid = livingDaemonPid(pidPath);
  if (!pid) {
    return { headlessTasks: 'no daemon', carriesMarker: false, mockGitHub: 'no daemon' };
  }
  let environment;
  try {
    environment = readEnvironment(pid);
  } catch {
    return { headlessTasks: 'unreadable', carriesMarker: false, mockGitHub: 'unreadable' };
  }
  return {
    headlessTasks: environment.includes(`${HEADLESS_TASKS_VAR}=off`) ? 'off' : 'on',
    carriesMarker: Boolean(marker) && environment.includes(`${TRIPWIRE_MARKER_VAR}=${marker}`),
    mockGitHub: mockGitHubURLIn(environment),
  };
}

function mockGitHubURLIn(environment) {
  const match = new RegExp(`(?:^|\\s)${MOCK_GITHUB_URL_VAR}=(\\S*)`).exec(environment);
  return match ? match[1] : 'missing';
}

export function readDaemonHeadlessSwitch(options = {}) {
  return readDaemonTripwireReceipt(options).headlessTasks;
}

export function readDaemonMockGitHubURL(options = {}) {
  return readDaemonTripwireReceipt(options).mockGitHub;
}

export function formatMockGitHubFailure({ scenarioId, expected, observed, pidPath = null }) {
  return [
    `mock GitHub: ${scenarioId} finished against a daemon that does not carry ${MOCK_GITHUB_URL_VAR}=${expected}.`,
    `  the daemon reads ${JSON.stringify(observed)}, so this run cannot be proved to have stayed off github.com.`,
    ...(pidPath ? [`daemon pid file: ${pidPath}`] : []),
    'the harness starts one mock per run and the app launch carries it into the daemon; a daemon that predates the run is stopped so the relaunch brings up one that carries it.',
  ].join('\n');
}

export function formatUnarmedDaemonFailure({ scenarioId, pid, pidPath, marker, read }) {
  return [
    `agent tripwire: ${scenarioId} must call no model, and the daemon it would run against cannot be proved armed.`,
    `daemon: pid ${pid} (${pidPath})`,
    `read: ${read}`,
    `expected: ${TRIPWIRE_MARKER_VAR}=${marker} and ${HEADLESS_TASKS_VAR}=off, or a non-production target this harness may stop so the app brings up an armed daemon.`,
    `a scenario that must run a real agent declares it instead: a scenarioCatalog.mjs entry, or allowRealAgents on createScenarioRunner.`,
  ].join('\n');
}

// A daemon started before this scenario carries another run's PATH and agent
// overrides, so the tripwire would watch a door the daemon never uses.
export function ensureDaemonCarriesTripwire({
  scenarioId = 'this scenario',
  marker,
  armed = false,
  mockGitHubURL = null,
  profile = currentHarnessProfile(),
  appPath = defaultAppPathForProfile(profile),
  pidPath = daemonPidFilePathForProfile(profile),
  log = (message) => console.log(`[agent-tripwire] ${message}`),
  readEnvironment = readProcessEnvironment,
  run = execFileSync,
} = {}) {
  const pid = livingDaemonPid(pidPath);
  if (!pid) {
    return { restarted: false, reason: 'no daemon running' };
  }
  const refuse = (read) => {
    throw new Error(formatUnarmedDaemonFailure({ scenarioId, pid, pidPath, marker, read }));
  };

  let environment = '';
  try {
    environment = readEnvironment(pid);
  } catch (error) {
    if (armed) {
      refuse(`the daemon environment is unreadable (${error?.message || error})`);
    }
    log(`could not read the environment of daemon pid ${pid}: ${error?.message || error}`);
    return { restarted: false, reason: 'daemon environment unreadable' };
  }
  const carriesMarker = environment.includes(`${TRIPWIRE_MARKER_VAR}=${marker}`);
  const carriesSwitch = !armed || environment.includes(`${HEADLESS_TASKS_VAR}=off`);
  const carriesMock = !mockGitHubURL || environment.includes(`${MOCK_GITHUB_URL_VAR}=${mockGitHubURL}`);
  if (carriesMarker && carriesSwitch && carriesMock) {
    return { restarted: false, reason: 'daemon already armed' };
  }

  try {
    assertFreshWorldTargetSafe({ profile, appPath });
  } catch (error) {
    if (armed) {
      refuse(`the daemon predates this tripwire and the target refuses a restart (${error?.message || error}); a production daemon is never restarted`);
    }
    log(`WARNING: daemon pid ${pid} predates this tripwire and the target refuses a restart (${error?.message || error}); session and headless execs may go unseen.`);
    return { restarted: false, reason: 'target refuses a daemon restart' };
  }

  const stale = carriesMock ? 'this tripwire' : 'this run\'s mock GitHub';
  log(`daemon pid ${pid} predates ${stale} — stopping it so the app relaunch brings one up armed.`);
  run(appDaemonInTree(appPath), ['daemon', 'stop'], {
    encoding: 'utf8',
    env: profileCliEnv(profile),
    stdio: 'pipe',
  });
  return { restarted: true, reason: 'daemon stopped' };
}
