package protocol

import "time"

const ProtocolVersion = "319"

const (
	ErrorCodeConflict             = "conflict"
	ErrorCodeUndeclaredCollection = "undeclared_collection"
	ErrorCodeInvalidQuery         = "invalid_query"
	ErrorCodeCollectionUndefined  = "collection_undefined"
	ErrorCodeCollectionRedeclared = "collection_redeclared"
	ErrorCodeSubscriptionLimit    = "subscription_limit"
	ErrorCodeReconcileOwed        = "reconcile_owed"
	ErrorCodeUnauthorizedClient   = "unauthorized_client"
)

const DocSubscriptionsPerClient = 64

const AgentMessageMaxChars = 32 * 1024

const CapabilityWorkspaceSessions = "workspace_sessions"

const CapabilityBrowserHost = "browser_host"

const CapabilityBinaryPtyOutput = "binary_pty_output"

const CapabilityKittyImages = "kitty_images"

type SessionAgent = string

const (
	SessionAgentClaude  SessionAgent = "claude"
	SessionAgentCodex   SessionAgent = "codex"
	SessionAgentCopilot SessionAgent = "copilot"
	SessionAgentShell   SessionAgent = "shell"
)

const (
	CmdClientHello                           = "client_hello"
	CmdRegister                              = "register"
	CmdDelegate                              = "delegate"
	CmdDelegationPreferencesGet              = "delegation_preferences_get"
	CmdDelegationPreferencesSave             = "delegation_preferences_save"
	CmdDelegationModels                      = "delegation_models"
	CmdDelegationRoles                       = "delegation_roles"
	CmdDelegateStatus                        = "delegate_status"
	CmdSetTicketStatus                       = "set_ticket_status"
	CmdTicketInbox                           = "ticket_inbox"
	CmdTicketList                            = "ticket_list"
	CmdTicketShow                            = "ticket_show"
	CmdTicketSubscribe                       = "ticket_subscribe"
	CmdTicketUnsubscribe                     = "ticket_unsubscribe"
	CmdTicketTake                            = "ticket_take"
	CmdTicketAttach                          = "ticket_attach"
	CmdTicketCreate                          = "ticket_create"
	CmdTicketComment                         = "ticket_comment"
	CmdDocDefine                             = "doc_define"
	CmdDocUndefine                           = "doc_undefine"
	CmdDocCollections                        = "doc_collections"
	CmdDocPut                                = "doc_put"
	CmdDocGet                                = "doc_get"
	CmdDocDelete                             = "doc_delete"
	CmdDocQuery                              = "doc_query"
	CmdDocCount                              = "doc_count"
	CmdDocSubscribe                          = "doc_subscribe"
	CmdDocUnsubscribe                        = "doc_unsubscribe"
	CmdAppList                               = "app_list"
	CmdAppStatus                             = "app_status"
	CmdAppSetEnabled                         = "app_set_enabled"
	CmdAppRemove                             = "app_remove"
	CmdAppApply                              = "app_apply"
	CmdAppRollback                           = "app_rollback"
	CmdAppLogs                               = "app_logs"
	CmdAppRuntimeStatus                      = "app_runtime_status"
	CmdAppRuntimeRestart                     = "app_runtime_restart"
	CmdAppWatch                              = "app_watch"
	CmdAppViewCrash                          = "app_view_crash"
	CmdAppCommand                            = "app_command"
	CmdPresentOpen                           = "present_open"
	CmdPresentFeedback                       = "present_feedback"
	CmdGetPresentations                      = "get_presentations"
	CmdGetPresentationRound                  = "get_presentation_round"
	CmdPresentSubmitRound                    = "present_submit_round"
	CmdPresentClose                          = "present_close"
	CmdNotebookList                          = "notebook_list"
	CmdNotebookRead                          = "notebook_read"
	CmdNotebookWrite                         = "notebook_write"
	CmdNotebookGuide                         = "notebook_guide"
	CmdJournalAppend                         = "journal_append"
	CmdNotebookBacklinks                     = "notebook_backlinks"
	CmdNotebookSendToChief                   = "notebook_send_to_chief"
	CmdTaskList                              = "task_list"
	CmdTaskRetry                             = "task_retry"
	CmdNotificationList                      = "notification_list"
	CmdNotificationMarkRead                  = "notification_mark_read"
	CmdFsList                                = "fs_list"
	CmdFsRead                                = "fs_read"
	CmdFsReadAsset                           = "fs_read_asset"
	CmdFsWrite                               = "fs_write"
	CmdFsRename                              = "fs_rename"
	CmdFsDelete                              = "fs_delete"
	CmdFsExists                              = "fs_exists"
	CmdFsWatch                               = "fs_watch"
	CmdFsUnwatch                             = "fs_unwatch"
	CmdFsIndex                               = "fs_index"
	CmdUnregister                            = "unregister"
	CmdState                                 = "state"
	CmdHookNotification                      = "hook_notification"
	CmdHookStopFailure                       = "hook_stop_failure"
	CmdHookCompaction                        = "hook_compaction"
	CmdSetSessionResumeID                    = "set_session_resume_id"
	CmdSessionInstructions                   = "session_instructions"
	CmdSessionTranscript                     = "session_transcript"
	CmdSessionList                           = "session_list"
	CmdSessionShow                           = "session_show"
	CmdSessionReopen                         = "session_reopen"
	CmdStateExplain                          = "state_explain"
	CmdAgentPeek                             = "agent_peek"
	CmdAgentMsg                              = "agent_msg"
	CmdAgentClose                            = "agent_close"
	CmdAgentInbox                            = "agent_inbox"
	CmdAgentMsgStatus                        = "agent_msg_status"
	CmdSeedPlant                             = "seed_plant"
	CmdSeedPlot                              = "seed_plot"
	CmdSeedList                              = "seed_list"
	CmdSeedSearch                            = "seed_search"
	CmdSeedShow                              = "seed_show"
	CmdSeedDocumentGet                       = "seed_document_get"
	CmdSeedArtifactTransfer                  = "seed_artifact_transfer"
	CmdSeedArtifactTarget                    = "seed_artifact_target"
	CmdSeedEdit                              = "seed_edit"
	CmdSeedTransition                        = "seed_transition"
	CmdSeedNote                              = "seed_note"
	CmdSeedNotes                             = "seed_notes"
	CmdSeedWatch                             = "seed_watch"
	CmdSeedLink                              = "seed_link"
	CmdSeedReady                             = "seed_ready"
	CmdSeedResume                            = "seed_resume"
	CmdSeedSendToChief                       = "seed_send_to_chief"
	CmdSeedReviewStart                       = "seed_review_start"
	CmdSeedReviewShow                        = "seed_review_show"
	CmdSeedReviewCancel                      = "seed_review_cancel"
	CmdSeedReviewRetry                       = "seed_review_retry"
	CmdSeedReviewKeep                        = "seed_review_keep"
	CmdSeedReviewDraft                       = "seed_review_draft"
	CmdCrewList                              = "crew_list"
	CmdCrewCharterGet                        = "crew_charter_get"
	CmdCrewCharterSet                        = "crew_charter_set"
	CmdCrewHandoffsGet                       = "crew_handoffs_get"
	CmdCrewHandoffGet                        = "crew_handoff_get"
	CmdCrewWake                              = "crew_wake"
	CmdCrewSleep                             = "crew_sleep"
	CmdCrewSet                               = "crew_set"
	CmdCrewRestart                           = "crew_restart"
	CmdCrewPrime                             = "crew_prime"
	CmdCrewHandoff                           = "crew_handoff"
	CmdStop                                  = "stop"
	CmdTodos                                 = "todos"
	CmdFilesEdited                           = "files_edited"
	CmdPullRequestCreated                    = "pull_request_created"
	CmdPullRequestForget                     = "pull_request_forget"
	CmdPullRequestWatch                      = "pull_request_watch"
	CmdPullRequestUnwatch                    = "pull_request_unwatch"
	CmdQuery                                 = "query"
	CmdHeartbeat                             = "heartbeat"
	CmdSessionSelected                       = "session_selected"
	CmdWorkspaceSelected                     = "workspace_selected"
	CmdTriggerNudge                          = "trigger_nudge"
	CmdSettleTurn                            = "settle_turn"
	CmdSnoozeTurn                            = "snooze_turn"
	CmdWakeTurn                              = "wake_turn"
	CmdCancelCountdown                       = "cancel_countdown"
	CmdMuteWorkspace                         = "mute_workspace"
	CmdPinWorkspace                          = "pin_workspace"
	CmdPinSession                            = "pin_session"
	CmdQueryPRs                              = "query_prs"
	CmdMutePR                                = "mute_pr"
	CmdMuteRepo                              = "mute_repo"
	CmdMuteAuthor                            = "mute_author"
	CmdCollapseRepo                          = "collapse_repo"
	CmdQueryRepos                            = "query_repos"
	CmdQueryAuthors                          = "query_authors"
	CmdFetchPRDetails                        = "fetch_pr_details"
	CmdRefreshPRs                            = "refresh_prs"
	CmdClearSessions                         = "clear_sessions"
	CmdClearWarnings                         = "clear_warnings"
	CmdPRVisited                             = "pr_visited"
	CmdListWorktrees                         = "list_worktrees"
	CmdCreateWorktree                        = "create_worktree"
	CmdDeleteWorktree                        = "delete_worktree"
	CmdWorktreeList                          = "worktree_list"
	CmdWorktreeKeep                          = "worktree_keep"
	CmdWorktreeSweepLog                      = "worktree_sweep_log"
	CmdWorktreeRefresh                       = "worktree_refresh"
	CmdGetSettings                           = "get_settings"
	CmdSetSetting                            = "set_setting"
	CmdListPlugins                           = "list_plugins"
	CmdInstallPlugin                         = "install_plugin"
	CmdInstallBundledPlugin                  = "install_bundled_plugin"
	CmdUninstallPlugin                       = "uninstall_plugin"
	CmdRemovePlugin                          = "remove_plugin"
	CmdSetPluginPriority                     = "set_plugin_priority"
	CmdAddEndpoint                           = "add_endpoint"
	CmdRemoveEndpoint                        = "remove_endpoint"
	CmdUpdateEndpoint                        = "update_endpoint"
	CmdListEndpoints                         = "list_endpoints"
	CmdSetEndpointRemoteWeb                  = "set_endpoint_remote_web"
	CmdBootstrapEndpoint                     = "bootstrap_endpoint"
	CmdApprovePR                             = "approve_pr"
	CmdMergePR                               = "merge_pr"
	CmdInjectTestPR                          = "inject_test_pr"
	CmdInjectTestSession                     = "inject_test_session"
	CmdGetRecentLocations                    = "get_recent_locations"
	CmdRecentFiles                           = "recent_files"
	CmdBrowseDirectory                       = "browse_directory"
	CmdInspectPath                           = "inspect_path"
	CmdListBranches                          = "list_branches"
	CmdCreateWorktreeFromBranch              = "create_worktree_from_branch"
	CmdGetDefaultBranch                      = "get_default_branch"
	CmdFetchRemotes                          = "fetch_remotes"
	CmdListRemoteBranches                    = "list_remote_branches"
	CmdEnsureRepo                            = "ensure_repo"
	CmdSubscribeGitStatus                    = "subscribe_git_status"
	CmdUnsubscribeGitStatus                  = "unsubscribe_git_status"
	CmdGetFileDiff                           = "get_file_diff"
	CmdGetRepoInfo                           = "get_repo_info"
	CmdWorkflowRunUpsert                     = "workflow_run_upsert"
	CmdWorkflowCallUpsert                    = "workflow_call_upsert"
	CmdWorkflowRunGet                        = "workflow_run_get"
	CmdWorkflowRunList                       = "workflow_run_list"
	CmdWorkflowRunCancel                     = "workflow_run_cancel"
	CmdAutomationApply                       = "automation_apply"
	CmdAutomationRun                         = "automation_run"
	CmdAutomationDefinitionsGet              = "automation_definitions_get"
	CmdAutomationDefinitionGet               = "automation_definition_get"
	CmdAutomationRunsGet                     = "automation_runs_get"
	CmdAutomationSetEnabled                  = "automation_set_enabled"
	CmdAutomationDelete                      = "automation_delete"
	CmdAutomationCleanup                     = "automation_cleanup"
	CmdAutomationValidate                    = "automation_validate"
	CmdSpawnSession                          = "spawn_session"
	CmdAttachSession                         = "attach_session"
	CmdDetachSession                         = "detach_session"
	CmdGetScreenSnapshot                     = "get_screen_snapshot"
	CmdGetKittyImage                         = "get_kitty_image"
	CmdPtyInput                              = "pty_input"
	CmdSupportSnapshot                       = "support_snapshot"
	CmdTerminalPointerActivity               = "terminal_pointer_activity"
	CmdBusStatusGet                          = "bus_status_get"
	CmdBusSetConsumerEnabled                 = "bus_set_consumer_enabled"
	CmdPtyResize                             = "pty_resize"
	CmdKillSession                           = "kill_session"
	CmdReloadSession                         = "reload_session"
	CmdSetClientPresence                     = "set_client_presence"
	CmdActivityStatus                        = "activity_status"
	CmdClearSessionActivity                  = "clear_session_activity"
	CmdSetTerminalTheme                      = "set_terminal_theme"
	CmdWorkspaceLayoutGet                    = "workspace_layout_get"
	CmdWorkspaceLayoutAddSessionPane         = "workspace_layout_add_session_pane"
	CmdWorkspaceLayoutClosePane              = "workspace_layout_close_pane"
	CmdWorkspaceLayoutFocusPane              = "workspace_layout_focus_pane"
	CmdWorkspaceLayoutRenamePane             = "workspace_layout_rename_pane"
	CmdWorkspaceLayoutSetSplitRatio          = "workspace_layout_set_split_ratio"
	CmdWorkspaceLayoutDockTile               = "workspace_layout_dock_tile"
	CmdWorkspaceLayoutUndockTile             = "workspace_layout_undock_tile"
	CmdWorkspaceLayoutUpdateTile             = "workspace_layout_update_tile"
	CmdWorkspaceLayoutMoveLeaf               = "workspace_layout_move_leaf"
	CmdWorkspaceLayoutMoveLeafToWorkspace    = "workspace_layout_move_leaf_to_workspace"
	CmdWorkspaceLayoutMoveLeafToNewWorkspace = "workspace_layout_move_leaf_to_new_workspace"
	CmdWorkspaceTileContentGet               = "workspace_tile_content_get"
	CmdOpenMarkdown                          = "open_markdown"
	CmdOpenSeed                              = "open_seed"
	CmdOpenSentFiles                         = "open_sent_files"
	CmdSessionMessagesGet                    = "session_messages_get"
	CmdSessionAnnotationsGet                 = "session_annotations_get"
	CmdSessionAnnotationsSave                = "session_annotations_save"
	CmdSessionAnnotationsClear               = "session_annotations_clear"
	CmdSessionAnnotationsSubmit              = "session_annotations_submit"
	CmdMarkdownAnnotationsGet                = "markdown_annotations_get"
	CmdMarkdownAnnotationsSave               = "markdown_annotations_save"
	CmdMarkdownAnnotationsClear              = "markdown_annotations_clear"
	CmdMarkdownAnnotationsSubmit             = "markdown_annotations_submit"
	CmdOpenBrowser                           = "open_browser"
	CmdBrowserControl                        = "browser_control"
	CmdBrowserControlResult                  = "browser_control_result"
	CmdRegisterWorkspace                     = "register_workspace"
	CmdUnregisterWorkspace                   = "unregister_workspace"
	CmdRenameSession                         = "rename_session"
	CmdRenameWorkspace                       = "rename_workspace"
	CmdSetWorkspaceRank                      = "set_workspace_rank"
	CmdSetChiefOfStaff                       = "set_chief_of_staff"
	CmdSetSessionContextWindowCap            = "set_session_context_window_cap"
)

const (
	CmdSetupCreate            = "setup_create"
	CmdSetupRename            = "setup_rename"
	CmdSetupDelete            = "setup_delete"
	CmdSetupSelect            = "setup_select"
	CmdDesktopCreate          = "desktop_create"
	CmdDesktopRename          = "desktop_rename"
	CmdDesktopSetShortcutSlot = "desktop_set_shortcut_slot"
	CmdDesktopReorder         = "desktop_reorder"
	CmdDesktopDelete          = "desktop_delete"
	CmdDesktopSetCurrent      = "desktop_set_current"
	CmdDesktopSetActivePane   = "desktop_set_active_pane"
	CmdDesktopPlaceSession    = "desktop_place_session"
	CmdDesktopMoveLeaf        = "desktop_move_leaf"
	CmdDesktopRemoveLeaf      = "desktop_remove_leaf"
	CmdDesktopSetSplitRatio   = "desktop_set_split_ratio"
	CmdDesktopDockTile        = "desktop_dock_tile"
	CmdDesktopUpdateTile      = "desktop_update_tile"
	CmdDesktopTileContentGet  = "desktop_tile_content_get"
)

const (
	EventSetupActionResult       = "setup_action_result"
	EventSetupsChanged           = "setups_changed"
	EventSetupArrangementChanged = "setup_arrangement_changed"
	EventDesktopTileContent      = "desktop_tile_content"
)

const (
	CmdAutoModeShow     = "automode_show"
	CmdAutoModeEnvSlot  = "automode_env_slot"
	CmdAutoModeEnvNotes = "automode_env_notes"
	CmdAutoModePropose  = "automode_propose"
	CmdAutoModeDenials  = "automode_denials"

	CmdAutoModeGet           = "automode_get"
	CmdAutoModePromote       = "automode_promote"
	CmdAutoModeDiscard       = "automode_discard"
	CmdAutoModeRuleAdd       = "automode_rule_add"
	CmdAutoModeRuleRemove    = "automode_rule_remove"
	CmdAutoModeHostAdd       = "automode_host_add"
	CmdAutoModeHostRemove    = "automode_host_remove"
	CmdAutoModePolicySet     = "automode_policy_set"
	CmdAutoModeLegacyDismiss = "automode_legacy_dismiss"
)

const EventAutoModeEnvSetResult = "automode_env_set_result"

const EventAutoModeStateChanged = "automode_state_changed"

const (
	EventAutomationApplyResult       = "automation_apply_result"
	EventAutomationValidateResult    = "automation_validate_result"
	EventAutomationDefinitionsResult = "automation_definitions_result"
	EventAutomationDefinitionResult  = "automation_definition_result"
	EventAutomationRunsResult        = "automation_runs_result"
	EventAutomationRunResult         = "automation_run_result"
	EventAutomationSetEnabledResult  = "automation_set_enabled_result"
	EventAutomationDeleteResult      = "automation_delete_result"
	EventAutomationCleanupResult     = "automation_cleanup_result"
)

const EventAutomationsChanged = "automations_changed"

const (
	EventSessionRegistered               = "session_registered"
	EventSessionUnregistered             = "session_unregistered"
	EventSessionCloseResult              = "session_close_result"
	EventSessionStateChanged             = "session_state_changed"
	EventWorkspaceRegistered             = "workspace_registered"
	EventWorkspaceUnregistered           = "workspace_unregistered"
	EventWorkspaceStateChanged           = "workspace_state_changed"
	EventNotebookChanged                 = "notebook_changed"
	EventSessionTodosUpdated             = "session_todos_updated"
	EventSessionsUpdated                 = "sessions_updated"
	EventPullRequestWatchResult          = "pull_request_watch_result"
	EventPullRequestUnwatchResult        = "pull_request_unwatch_result"
	EventRenameResult                    = "rename_result"
	EventChiefOfStaffResult              = "chief_of_staff_result"
	EventSessionContextWindowCapResult   = "session_context_window_cap_result"
	EventGardenSeedsUpdated              = "garden_seeds_updated"
	EventGardenReviewUpdated             = "garden_review_updated"
	EventAppsUpdated                     = "apps_updated"
	EventAppCommandResult                = "app_command_result"
	EventDocSubscriptionDelivery         = "doc_subscription_delivery"
	EventDocSubscriptionEnded            = "doc_subscription_ended"
	EventCrewUpdated                     = "crew_updated"
	EventCrewCharterGetResult            = "crew_charter_get_result"
	EventCrewCharterSetResult            = "crew_charter_set_result"
	EventCrewHandoffsGetResult           = "crew_handoffs_get_result"
	EventCrewHandoffGetResult            = "crew_handoff_get_result"
	EventCrewWakeResult                  = "crew_wake_result"
	EventCrewSleepResult                 = "crew_sleep_result"
	EventCrewSetResult                   = "crew_set_result"
	EventCrewRestartResult               = "crew_restart_result"
	EventTicketAttachResult              = "ticket_attach_result"
	EventGetPresentationsResult          = "get_presentations_result"
	EventGetPresentationRoundResult      = "get_presentation_round_result"
	EventPresentSubmitRoundResult        = "present_submit_round_result"
	EventPresentCloseResult              = "present_close_result"
	EventPresentationAdded               = "presentation_added"
	EventPresentationUpdated             = "presentation_updated"
	EventDelegateResult                  = "delegate_result"
	EventDelegationOperation             = "delegation_operation"
	EventNotebookListResult              = "notebook_list_result"
	EventNotebookReadResult              = "notebook_read_result"
	EventNotebookBacklinksResult         = "notebook_backlinks_result"
	EventNotebookWriteResult             = "notebook_write_result"
	EventNotebookSendToChiefResult       = "notebook_send_to_chief_result"
	EventTaskListResult                  = "task_list_result"
	EventTaskRetryResult                 = "task_retry_result"
	EventTasksChanged                    = "tasks_changed"
	EventSessionListResult               = "session_list_result"
	EventSessionShowResult               = "session_show_result"
	EventSessionReopenResult             = "session_reopen_result"
	EventSessionReopenRefreshed          = "session_reopen_refreshed"
	EventSessionClosed                   = "session_closed"
	EventNotificationListResult          = "notification_list_result"
	EventNotificationMarkReadResult      = "notification_mark_read_result"
	EventNotificationsUpdated            = "notifications_updated"
	EventFsListResult                    = "fs_list_result"
	EventFsReadResult                    = "fs_read_result"
	EventFsReadAssetResult               = "fs_read_asset_result"
	EventFsWriteResult                   = "fs_write_result"
	EventFsRenameResult                  = "fs_rename_result"
	EventFsDeleteResult                  = "fs_delete_result"
	EventFsExistsResult                  = "fs_exists_result"
	EventFsWatchResult                   = "fs_watch_result"
	EventFsUnwatchResult                 = "fs_unwatch_result"
	EventFsIndexResult                   = "fs_index_result"
	EventFsChanged                       = "fs_changed"
	EventPRsUpdated                      = "prs_updated"
	EventReposUpdated                    = "repos_updated"
	EventAuthorsUpdated                  = "authors_updated"
	EventInitialState                    = "initial_state"
	EventEndpointStatusChanged           = "endpoint_status_changed"
	EventEndpointsUpdated                = "endpoints_updated"
	EventEndpointActionResult            = "endpoint_action_result"
	EventPRActionResult                  = "pr_action_result"
	EventRefreshPRsResult                = "refresh_prs_result"
	EventFetchPRDetailsResult            = "fetch_pr_details_result"
	EventBranchChanged                   = "branch_changed"
	EventWorktreeCreated                 = "worktree_created"
	EventWorktreeDeleted                 = "worktree_deleted"
	EventWorktreesUpdated                = "worktrees_updated"
	EventWorktreeStateChanged            = "worktree_state_changed"
	EventWorktreeSwept                   = "worktree_swept"
	EventWorktreeListResult              = "worktree_list_result"
	EventWorktreeKeepResult              = "worktree_keep_result"
	EventWorktreeSweepLogResult          = "worktree_sweep_log_result"
	EventWorktreeRefreshResult           = "worktree_refresh_result"
	EventCreateWorktreeResult            = "create_worktree_result"
	EventDeleteWorktreeResult            = "delete_worktree_result"
	EventGitOperationStarted             = "git_operation_started"
	EventGitOperationFinished            = "git_operation_finished"
	EventSettingsUpdated                 = "settings_updated"
	EventGitHubHostsUpdated              = "github_hosts_updated"
	EventPluginsUpdated                  = "plugins_updated"
	EventPluginActionResult              = "plugin_action_result"
	EventRateLimited                     = "rate_limited"
	EventRecentLocationsResult           = "recent_locations_result"
	EventRecentFilesResult               = "recent_files_result"
	EventBrowseDirectoryResult           = "browse_directory_result"
	EventInspectPathResult               = "inspect_path_result"
	EventBranchesResult                  = "branches_result"
	EventGetDefaultBranchResult          = "get_default_branch_result"
	EventFetchRemotesResult              = "fetch_remotes_result"
	EventListRemoteBranchesResult        = "list_remote_branches_result"
	EventEnsureRepoResult                = "ensure_repo_result"
	EventGitStatusUpdate                 = "git_status_update"
	EventFileDiffResult                  = "file_diff_result"
	EventGetRepoInfoResult               = "get_repo_info_result"
	EventWorkflowRunUpdated              = "workflow_run_updated"
	EventWorkflowActionResult            = "workflow_action_result"
	EventPtyOutput                       = "pty_output"
	EventPtyInputProbeResult             = "pty_input_probe_result"
	EventSupportSnapshotResult           = "support_snapshot_result"
	EventSpawnResult                     = "spawn_result"
	EventReloadSessionResult             = "reload_session_result"
	EventAttachResult                    = "attach_result"
	EventGetScreenSnapshotResult         = "get_screen_snapshot_result"
	EventSessionExited                   = "session_exited"
	EventPtyDesync                       = "pty_desync"
	EventKittyPlacements                 = "kitty_placements"
	EventKittyImageResult                = "kitty_image_result"
	EventRuntimeRespawned                = "runtime_respawned"
	EventPtyResized                      = "pty_resized"
	EventWorkspaceLayout                 = "workspace_layout"
	EventWorkspaceLayoutUpdated          = "workspace_layout_updated"
	EventWorkspaceLayoutActionResult     = "workspace_layout_action_result"
	EventWorkspaceTileContent            = "workspace_tile_content"
	EventOpenMarkdownResult              = "open_markdown_result"
	EventOpenSeedResult                  = "open_seed_result"
	EventSeedDocumentGetResult           = "seed_document_get_result"
	EventSeedArtifactTransferResult      = "seed_artifact_transfer_result"
	EventSeedArtifactTargetResult        = "seed_artifact_target_result"
	EventSeedResumeResult                = "seed_resume_result"
	EventSeedSendToChiefResult           = "seed_send_to_chief_result"
	EventSeedReviewResult                = "seed_review_result"
	EventSeedReviewDraftResult           = "seed_review_draft_result"
	EventSeedTransitionResult            = "seed_transition_result"
	EventSeedNoteResult                  = "seed_note_result"
	EventSessionMessagesGetResult        = "session_messages_get_result"
	EventSessionMessagesChanged          = "session_messages_changed"
	EventBusStatusResult                 = "bus_status_result"
	EventBusSetConsumerEnabledResult     = "bus_set_consumer_enabled_result"
	EventAutoModeStateResult             = "automode_state_result"
	EventAutoModePromoteResult           = "automode_promote_result"
	EventAutoModeDiscardResult           = "automode_discard_result"
	EventAutoModeConfigResult            = "automode_config_result"
	EventSessionAnnotationsGetResult     = "session_annotations_get_result"
	EventSessionAnnotationsSaveResult    = "session_annotations_save_result"
	EventSessionAnnotationsClearResult   = "session_annotations_clear_result"
	EventSessionAnnotationsSubmitResult  = "session_annotations_submit_result"
	EventMarkdownAnnotationsGetResult    = "markdown_annotations_get_result"
	EventMarkdownAnnotationsSaveResult   = "markdown_annotations_save_result"
	EventMarkdownAnnotationsClearResult  = "markdown_annotations_clear_result"
	EventMarkdownAnnotationsSubmitResult = "markdown_annotations_submit_result"
	EventBrowserControlResponse          = "browser_control_response"
	EventBrowserControlRequest           = "browser_control_request"
	EventCommandError                    = "command_error"
	EventClientEvictionNotice            = "client_eviction_notice"
)

const (
	StateLaunching       = "launching"
	StateWorking         = "working"
	StateWaitingInput    = "waiting_input"
	StateIdle            = "idle"
	StatePendingApproval = "pending_approval"
	StateScheduled       = "scheduled"
	StateUnknown         = "unknown"
)

const (
	AgentShellValue = "shell"
)

const (
	PRStateWaiting = "waiting"
)

const (
	PRReasonReadyToMerge     = "ready_to_merge"
	PRReasonCIFailed         = "ci_failed"
	PRReasonChangesRequested = "changes_requested"
	PRReasonReviewNeeded     = "review_needed"
)

const (
	HeatHotDuration  = 3 * time.Minute
	HeatWarmDuration = 10 * time.Minute
	HeatHotInterval  = 30 * time.Second
	HeatWarmInterval = 2 * time.Minute
	HeatColdInterval = 10 * time.Minute
)

func (pr *PR) NeedsDetailRefresh() bool {
	if !pr.DetailsFetched {
		return true
	}
	lastUpdated := Timestamp(pr.LastUpdated).Time()
	detailsFetchedAt := Timestamp(Deref(pr.DetailsFetchedAt)).Time()

	if lastUpdated.After(detailsFetchedAt) {
		return true
	}
	if time.Since(detailsFetchedAt) > 5*time.Minute {
		return true
	}
	return false
}

const (
	EventDelegationPreferencesResult  = "delegation_preferences_result"
	EventDelegationPreferencesChanged = "delegation_preferences_changed"
	EventDelegationModelsResult       = "delegation_models_result"
)
