package protocol

import (
	"encoding/json"
	"errors"
	"fmt"
)

func decodeInto[T any](data []byte) (any, error) {
	msg := new(T)
	if err := json.Unmarshal(data, msg); err != nil {
		return nil, err
	}
	return msg, nil
}

var messageDecoders = map[string]func([]byte) (any, error){
	CmdClientHello:                   decodeInto[ClientHelloMessage],
	CmdDelegate:                      decodeInto[DelegateMessage],
	CmdAutomationApply:               decodeInto[AutomationApplyMessage],
	CmdAutomationRun:                 decodeInto[AutomationRunMessage],
	CmdAutomationDefinitionsGet:      decodeInto[AutomationDefinitionsGetMessage],
	CmdAutomationDefinitionGet:       decodeInto[AutomationDefinitionGetMessage],
	CmdAutomationValidate:            decodeInto[AutomationValidateMessage],
	CmdAutomationRunsGet:             decodeInto[AutomationRunsGetMessage],
	CmdAutomationSetEnabled:          decodeInto[AutomationSetEnabledMessage],
	CmdAutomationDelete:              decodeInto[AutomationDeleteMessage],
	CmdAutomationCleanup:             decodeInto[AutomationCleanupMessage],
	CmdDelegationPreferencesGet:      decodeInto[DelegationPreferencesGetMessage],
	CmdDelegationPreferencesSave:     decodeInto[DelegationPreferencesSaveMessage],
	CmdDelegationPreferencesShow:     decodeInto[DelegationPreferencesShowMessage],
	CmdDelegationPreferencesCommit:   decodeInto[DelegationPreferencesCommitMessage],
	CmdDelegationPreferencesHistory:  decodeInto[DelegationPreferencesHistoryMessage],
	CmdDelegationPreferencesRollback: decodeInto[DelegationPreferencesRollbackMessage],
	CmdDelegationModels:              decodeInto[DelegationModelsMessage],
	CmdDelegationRoles:               decodeInto[DelegationRolesMessage],
	CmdDelegateStatus:                decodeInto[DelegateStatusMessage],
	CmdDocDefine:                     decodeInto[DocDefineMessage],
	CmdDocUndefine:                   decodeInto[DocUndefineMessage],
	CmdDocCollections:                decodeInto[DocCollectionsMessage],
	CmdDocPut:                        decodeInto[DocPutMessage],
	CmdDocGet:                        decodeInto[DocGetMessage],
	CmdDocDelete:                     decodeInto[DocDeleteMessage],
	CmdDocQuery:                      decodeInto[DocQueryMessage],
	CmdDocCount:                      decodeInto[DocCountMessage],
	CmdDocSubscribe:                  decodeInto[DocSubscribeMessage],
	CmdDocUnsubscribe:                decodeInto[DocUnsubscribeMessage],
	CmdAutoModeShow:                  decodeInto[AutoModeShowMessage],
	CmdAutoModeEnvSlot:               decodeInto[AutoModeEnvSlotMessage],
	CmdAutoModeEnvNotes:              decodeInto[AutoModeEnvNotesMessage],
	CmdAutoModePropose:               decodeInto[AutoModeProposeMessage],
	CmdAutoModeDenials:               decodeInto[AutoModeDenialsMessage],
	CmdPresentOpen:                   decodeInto[PresentOpenMessage],
	CmdPresentFeedback:               decodeInto[PresentFeedbackMessage],
	CmdGetPresentations:              decodeInto[GetPresentationsMessage],
	CmdGetPresentationRound:          decodeInto[GetPresentationRoundMessage],
	CmdPresentSubmitRound:            decodeInto[PresentSubmitRoundMessage],
	CmdPresentClose:                  decodeInto[PresentCloseMessage],
	CmdNotebookList:                  decodeInto[NotebookListMessage],
	CmdNotebookRead:                  decodeInto[NotebookReadMessage],
	CmdNotebookWrite:                 decodeInto[NotebookWriteMessage],
	CmdNotebookGuide:                 decodeInto[NotebookGuideMessage],
	CmdJournalAppend:                 decodeInto[JournalAppendMessage],
	CmdNotebookBacklinks:             decodeInto[NotebookBacklinksMessage],
	CmdNotebookSendToChief:           decodeInto[NotebookSendToChiefMessage],
	CmdTaskList:                      decodeInto[TaskListMessage],
	CmdTaskRetry:                     decodeInto[TaskRetryMessage],
	CmdNotificationList:              decodeInto[NotificationListMessage],
	CmdNotificationMarkRead:          decodeInto[NotificationMarkReadMessage],
	CmdFsList:                        decodeInto[FsListMessage],
	CmdFsRead:                        decodeInto[FsReadMessage],
	CmdFsReadAsset:                   decodeInto[FsReadAssetMessage],
	CmdFsWrite:                       decodeInto[FsWriteMessage],
	CmdFsRename:                      decodeInto[FsRenameMessage],
	CmdFsDelete:                      decodeInto[FsDeleteMessage],
	CmdFsExists:                      decodeInto[FsExistsMessage],
	CmdFsWatch:                       decodeInto[FsWatchMessage],
	CmdFsUnwatch:                     decodeInto[FsUnwatchMessage],
	CmdFsIndex:                       decodeInto[FsIndexMessage],
	CmdUnregister:                    decodeInto[UnregisterMessage],
	CmdState:                         decodeInto[StateMessage],
	CmdHookNotification:              decodeInto[HookNotificationMessage],
	CmdHookStopFailure:               decodeInto[HookStopFailureMessage],
	CmdHookCompaction:                decodeInto[HookCompactionMessage],
	CmdSetSessionResumeID:            decodeInto[SetSessionResumeIDMessage],
	CmdSessionInstructions:           decodeInto[SessionInstructionsMessage],
	CmdSessionTranscript:             decodeInto[SessionTranscriptMessage],
	CmdSessionList:                   decodeInto[SessionListMessage],
	CmdSessionShow:                   decodeInto[SessionShowMessage],
	CmdSessionReopen:                 decodeInto[SessionReopenMessage],
	CmdStateExplain:                  decodeInto[StateExplainMessage],
	CmdAgentPeek:                     decodeInto[AgentPeekMessage],
	CmdAgentMsg:                      decodeInto[AgentMsgMessage],
	CmdAgentClose:                    decodeInto[AgentCloseMessage],
	CmdAgentInbox:                    decodeInto[AgentInboxMessage],
	CmdAgentMsgStatus:                decodeInto[AgentMsgStatusMessage],
	CmdCrewList:                      decodeInto[CrewListMessage],
	CmdCrewWake:                      decodeInto[CrewWakeMessage],
	CmdCrewSleep:                     decodeInto[CrewSleepMessage],
	CmdCrewSet:                       decodeInto[CrewSetMessage],
	CmdCrewPrime:                     decodeInto[CrewPrimeMessage],
	CmdCrewHandoff:                   decodeInto[CrewHandoffMessage],
	CmdCrewCharterGet:                decodeInto[CrewCharterGetMessage],
	CmdCrewCharterSet:                decodeInto[CrewCharterSetMessage],
	CmdCrewHandoffsGet:               decodeInto[CrewHandoffsGetMessage],
	CmdCrewHandoffGet:                decodeInto[CrewHandoffGetMessage],
	CmdCrewRestart:                   decodeInto[CrewRestartMessage],
	CmdSeedPlant:                     decodeInto[SeedPlantMessage],
	CmdSeedPlot:                      decodeInto[SeedPlotMessage],
	CmdSeedList:                      decodeInto[SeedListMessage],
	CmdSeedSearch:                    decodeInto[SeedSearchMessage],
	CmdSeedShow:                      decodeInto[SeedShowMessage],
	CmdSeedDocumentGet:               decodeInto[SeedDocumentGetMessage],
	CmdSeedArtifactTransfer:          decodeInto[SeedArtifactTransferMessage],
	CmdSeedArtifactTarget:            decodeInto[SeedArtifactTargetMessage],
	CmdSeedEdit:                      decodeInto[SeedEditMessage],
	CmdSeedTransition:                decodeInto[SeedTransitionMessage],
	CmdSeedNote:                      decodeInto[SeedNoteMessage],
	CmdSeedNotes:                     decodeInto[SeedNotesMessage],
	CmdSeedWatch:                     decodeInto[SeedWatchMessage],
	CmdSeedLink:                      decodeInto[SeedLinkMessage],
	CmdSeedReady:                     decodeInto[SeedReadyMessage],
	CmdSeedResume:                    decodeInto[SeedResumeMessage],
	CmdSeedSendToChief:               decodeInto[SeedSendToChiefMessage],
	CmdSeedReviewStart:               decodeInto[SeedReviewStartMessage],
	CmdSeedReviewShow:                decodeInto[SeedReviewShowMessage],
	CmdSeedReviewCancel:              decodeInto[SeedReviewCancelMessage],
	CmdSeedReviewRetry:               decodeInto[SeedReviewRetryMessage],
	CmdSeedReviewKeep:                decodeInto[SeedReviewKeepMessage],
	CmdSeedReviewDraft:               decodeInto[SeedReviewDraftMessage],
	CmdStop:                          decodeInto[StopMessage],
	CmdFilesEdited:                   decodeInto[FilesEditedMessage],
	CmdPullRequestCreated:            decodeInto[PullRequestCreatedMessage],
	CmdPullRequestForget:             decodeInto[PullRequestForgetMessage],
	CmdPullRequestWatch:              decodeInto[PullRequestWatchMessage],
	CmdPullRequestUnwatch:            decodeInto[PullRequestUnwatchMessage],
	CmdQuery:                         decodeInto[QueryMessage],
	CmdHeartbeat:                     decodeInto[HeartbeatMessage],
	CmdSetSessionPriority:            decodeInto[SetSessionPriorityMessage],
	CmdSettleTurn:                    decodeInto[SettleTurnMessage],
	CmdSnoozeTurn:                    decodeInto[SnoozeTurnMessage],
	CmdWakeTurn:                      decodeInto[WakeTurnMessage],
	CmdCancelCountdown:               decodeInto[CancelCountdownMessage],
	CmdQueryPRs:                      decodeInto[QueryPRsMessage],
	CmdMutePR:                        decodeInto[MutePRMessage],
	CmdMuteRepo:                      decodeInto[MuteRepoMessage],
	CmdMuteAuthor:                    decodeInto[MuteAuthorMessage],
	CmdCollapseRepo:                  decodeInto[CollapseRepoMessage],
	CmdQueryRepos:                    decodeInto[QueryReposMessage],
	CmdQueryAuthors:                  decodeInto[QueryAuthorsMessage],
	CmdFetchPRDetails:                decodeInto[FetchPRDetailsMessage],
	CmdRefreshPRs:                    decodeInto[RefreshPRsMessage],
	CmdClearWarnings:                 decodeInto[ClearWarningsMessage],
	CmdPRVisited:                     decodeInto[PRVisitedMessage],
	CmdListWorktrees:                 decodeInto[ListWorktreesMessage],
	CmdCreateWorktree:                decodeInto[CreateWorktreeMessage],
	CmdDeleteWorktree:                decodeInto[DeleteWorktreeMessage],
	CmdKeptConversationList:          decodeInto[KeptConversationListMessage],
	CmdKeptConversationKeep:          decodeInto[KeptConversationKeepMessage],
	CmdKeptConversationForget:        decodeInto[KeptConversationForgetMessage],
	CmdWorktreeList:                  decodeInto[WorktreeListMessage],
	CmdWorktreeKeep:                  decodeInto[WorktreeKeepMessage],
	CmdWorktreeSweepLog:              decodeInto[WorktreeSweepLogMessage],
	CmdWorktreeRefresh:               decodeInto[WorktreeRefreshMessage],
	CmdGetSettings:                   decodeInto[GetSettingsMessage],
	CmdSetSetting:                    decodeInto[SetSettingMessage],
	CmdListPlugins:                   decodeInto[ListPluginsMessage],
	CmdInstallPlugin:                 decodeInto[InstallPluginMessage],
	CmdInstallBundledPlugin:          decodeInto[InstallBundledPluginMessage],
	CmdUninstallPlugin:               decodeInto[UninstallPluginMessage],
	CmdRemovePlugin:                  decodeInto[RemovePluginMessage],
	CmdSetPluginPriority:             decodeInto[SetPluginPriorityMessage],
	CmdAddEndpoint:                   decodeInto[AddEndpointMessage],
	CmdRemoveEndpoint:                decodeInto[RemoveEndpointMessage],
	CmdUpdateEndpoint:                decodeInto[UpdateEndpointMessage],
	CmdListEndpoints:                 decodeInto[ListEndpointsMessage],
	CmdSetEndpointRemoteWeb:          decodeInto[SetEndpointRemoteWebMessage],
	CmdBootstrapEndpoint:             decodeInto[BootstrapEndpointMessage],
	CmdApprovePR:                     decodeInto[ApprovePRMessage],
	CmdMergePR:                       decodeInto[MergePRMessage],
	CmdInjectTestPR:                  decodeInto[InjectTestPRMessage],
	CmdInjectTestSession:             decodeInto[InjectTestSessionMessage],
	CmdGetRecentLocations:            decodeInto[GetRecentLocationsMessage],
	CmdGetCommandUsage:               decodeInto[GetCommandUsageMessage],
	CmdRecordCommandUsage:            decodeInto[RecordCommandUsageMessage],
	CmdRecentFiles:                   decodeInto[RecentFilesMessage],
	CmdBrowseDirectory:               decodeInto[BrowseDirectoryMessage],
	CmdInspectPath:                   decodeInto[InspectPathMessage],
	CmdListBranches:                  decodeInto[ListBranchesMessage],
	CmdCreateWorktreeFromBranch:      decodeInto[CreateWorktreeFromBranchMessage],
	CmdGetDefaultBranch:              decodeInto[GetDefaultBranchMessage],
	CmdFetchRemotes:                  decodeInto[FetchRemotesMessage],
	CmdListRemoteBranches:            decodeInto[ListRemoteBranchesMessage],
	CmdEnsureRepo:                    decodeInto[EnsureRepoMessage],
	CmdSubscribeGitStatus:            decodeInto[SubscribeGitStatusMessage],
	CmdUnsubscribeGitStatus:          decodeInto[UnsubscribeGitStatusMessage],
	CmdGetFileDiff:                   decodeInto[GetFileDiffMessage],
	CmdGetRepoInfo:                   decodeInto[GetRepoInfoMessage],
	CmdWorkflowRunUpsert:             decodeInto[WorkflowRunUpsertMessage],
	CmdWorkflowCallUpsert:            decodeInto[WorkflowCallUpsertMessage],
	CmdWorkflowRunGet:                decodeInto[WorkflowRunGetMessage],
	CmdWorkflowRunList:               decodeInto[WorkflowRunListMessage],
	CmdWorkflowRunCancel:             decodeInto[WorkflowRunCancelMessage],
	CmdSpawnSession:                  decodeInto[SpawnSessionMessage],
	CmdAttachSession:                 decodeInto[AttachSessionMessage],
	CmdDetachSession:                 decodeInto[DetachSessionMessage],
	CmdGetScreenSnapshot:             decodeInto[GetScreenSnapshotMessage],
	CmdGetKittyImage:                 decodeInto[GetKittyImageMessage],
	CmdPtyInput:                      decodeInto[PtyInputMessage],
	CmdSupportSnapshot:               decodeInto[SupportSnapshotMessage],
	CmdTerminalPointerActivity:       decodeInto[TerminalPointerActivityMessage],
	CmdBusStatusGet:                  decodeInto[BusStatusGetMessage],
	CmdAutoModeGet:                   decodeInto[AutoModeGetMessage],
	CmdAutoModePromote:               decodeInto[AutoModePromoteMessage],
	CmdAutoModeDiscard:               decodeInto[AutoModeDiscardMessage],
	CmdAutoModeRuleAdd:               decodeInto[AutoModeRuleAddMessage],
	CmdAutoModeRuleRemove:            decodeInto[AutoModeRuleRemoveMessage],
	CmdAutoModeHostAdd:               decodeInto[AutoModeHostAddMessage],
	CmdAutoModeHostRemove:            decodeInto[AutoModeHostRemoveMessage],
	CmdAutoModePolicySet:             decodeInto[AutoModePolicySetMessage],
	CmdAutoModeLegacyDismiss:         decodeInto[AutoModeLegacyDismissMessage],
	CmdBusSetConsumerEnabled:         decodeInto[BusSetConsumerEnabledMessage],
	CmdPtyResize:                     decodeInto[PtyResizeMessage],
	CmdKillSession:                   decodeInto[KillSessionMessage],
	CmdReloadSession:                 decodeInto[ReloadSessionMessage],
	CmdSetClientPresence:             decodeInto[SetClientPresenceMessage],
	CmdActivityStatus:                decodeInto[ActivityStatusMessage],
	CmdClearSessionActivity:          decodeInto[ClearSessionActivityMessage],
	CmdSetTerminalTheme:              decodeInto[SetTerminalThemeMessage],
	CmdOpenMarkdown:                  decodeInto[OpenMarkdownMessage],
	CmdOpenSeed:                      decodeInto[OpenSeedMessage],
	CmdOpenSentFiles:                 decodeInto[OpenSentFilesMessage],
	CmdSessionMessagesGet:            decodeInto[SessionMessagesGetMessage],
	CmdSessionAnnotationsGet:         decodeInto[SessionAnnotationsGetMessage],
	CmdSessionAnnotationsSave:        decodeInto[SessionAnnotationsSaveMessage],
	CmdSessionAnnotationsClear:       decodeInto[SessionAnnotationsClearMessage],
	CmdSessionAnnotationsSubmit:      decodeInto[SessionAnnotationsSubmitMessage],
	CmdMarkdownAnnotationsGet:        decodeInto[MarkdownAnnotationsGetMessage],
	CmdMarkdownAnnotationsSave:       decodeInto[MarkdownAnnotationsSaveMessage],
	CmdMarkdownAnnotationsClear:      decodeInto[MarkdownAnnotationsClearMessage],
	CmdMarkdownAnnotationsSubmit:     decodeInto[MarkdownAnnotationsSubmitMessage],
	CmdOpenBrowser:                   decodeInto[OpenBrowserMessage],
	CmdBrowserControl:                decodeInto[BrowserControlMessage],
	CmdBrowserControlResult:          decodeInto[BrowserControlResultMessage],
	CmdRenameSession:                 decodeInto[RenameSessionMessage],
	CmdProfileCreate:                 decodeInto[ProfileCreateMessage],
	CmdProfileRename:                 decodeInto[ProfileRenameMessage],
	CmdProfileDelete:                 decodeInto[ProfileDeleteMessage],
	CmdProfileSelect:                 decodeInto[ProfileSelectMessage],
	CmdLaunchDesktopGet:              decodeInto[LaunchDesktopGetMessage],
	CmdLaunchDesktopSet:              decodeInto[LaunchDesktopSetMessage],
	CmdMigrationGet:                  decodeInto[MigrationGetMessage],
	CmdMigrationKeep:                 decodeInto[MigrationKeepMessage],
	CmdMigrationMove:                 decodeInto[MigrationMoveMessage],
	CmdMigrationSuggest:              decodeInto[MigrationSuggestMessage],
	CmdMigrationUndo:                 decodeInto[MigrationUndoMessage],
	CmdMigrationFinish:               decodeInto[MigrationFinishMessage],
	CmdDesktopCreate:                 decodeInto[DesktopCreateMessage],
	CmdDesktopRename:                 decodeInto[DesktopRenameMessage],
	CmdDesktopReorder:                decodeInto[DesktopReorderMessage],
	CmdDesktopSetCurrent:             decodeInto[DesktopSetCurrentMessage],
	CmdDesktopSetActivePane:          decodeInto[DesktopSetActivePaneMessage],
	CmdDesktopPlaceSession:           decodeInto[DesktopPlaceSessionMessage],
	CmdDesktopShowSession:            decodeInto[DesktopShowSessionMessage],
	CmdDesktopMoveSession:            decodeInto[DesktopMoveSessionMessage],
	CmdDesktopShowLeaf:               decodeInto[DesktopShowLeafMessage],
	CmdDesktopMoveLeaf:               decodeInto[DesktopMoveLeafMessage],
	CmdDesktopRemoveLeaf:             decodeInto[DesktopRemoveLeafMessage],
	CmdDesktopDockTile:               decodeInto[DesktopDockTileMessage],
	CmdDesktopUpdateTile:             decodeInto[DesktopUpdateTileMessage],
	CmdDesktopSetSplitRatio:          decodeInto[DesktopSetSplitRatioMessage],
	CmdSetChiefOfStaff:               decodeInto[SetChiefOfStaffMessage],
	CmdSetSessionContextWindowCap:    decodeInto[SetSessionContextWindowCapMessage],
}

func ParseMessage(data []byte) (string, any, error) {
	var peek struct {
		Cmd string `json:"cmd"`
	}
	if err := json.Unmarshal(data, &peek); err != nil {
		return "", nil, err
	}
	if peek.Cmd == "" {
		return "", nil, errors.New("missing cmd field")
	}
	decode, known := messageDecoders[peek.Cmd]
	if !known {
		return "", nil, errors.New("unknown command: " + peek.Cmd)
	}
	msg, err := decode(data)
	if err != nil {
		return "", nil, fmt.Errorf("unmarshal %s: %w", peek.Cmd, err)
	}
	return peek.Cmd, msg, nil
}
